// Code generated by MockGen. DO NOT EDIT.
// Source: fileops/fileops.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	fileops "github.com/mmichie/intu/fileops"
)

// MockFileOperator is a mock of FileOperator interface.
type MockFileOperator struct {
	ctrl     *gomock.Controller
	recorder *MockFileOperatorMockRecorder
}

// MockFileOperatorMockRecorder is the mock recorder for MockFileOperator.
type MockFileOperatorMockRecorder struct {
	mock *MockFileOperator
}

// NewMockFileOperator creates a new mock instance.
func NewMockFileOperator(ctrl *gomock.Controller) *MockFileOperator {
	mock := &MockFileOperator{ctrl: ctrl}
	mock.recorder = &MockFileOperatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileOperator) EXPECT() *MockFileOperatorMockRecorder {
	return m.recorder
}

// FindFiles mocks base method.
func (m *MockFileOperator) FindFiles(ctx context.Context, pattern string, options fileops.Options) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFiles", ctx, pattern, options)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFiles indicates an expected call of FindFiles.
func (mr *MockFileOperatorMockRecorder) FindFiles(ctx, pattern, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFiles", reflect.TypeOf((*MockFileOperator)(nil).FindFiles), ctx, pattern, options)
}

// GetBasicFileInfo mocks base method.
func (m *MockFileOperator) GetBasicFileInfo(ctx context.Context, path, content string) (fileops.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBasicFileInfo", ctx, path, content)
	ret0, _ := ret[0].(fileops.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasicFileInfo indicates an expected call of GetBasicFileInfo.
func (mr *MockFileOperatorMockRecorder) GetBasicFileInfo(ctx, path, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasicFileInfo", reflect.TypeOf((*MockFileOperator)(nil).GetBasicFileInfo), ctx, path, content)
}

// GetExtendedFileInfo mocks base method.
func (m *MockFileOperator) GetExtendedFileInfo(ctx context.Context, path, content string) (fileops.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExtendedFileInfo", ctx, path, content)
	ret0, _ := ret[0].(fileops.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExtendedFileInfo indicates an expected call of GetExtendedFileInfo.
func (mr *MockFileOperatorMockRecorder) GetExtendedFileInfo(ctx, path, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExtendedFileInfo", reflect.TypeOf((*MockFileOperator)(nil).GetExtendedFileInfo), ctx, path, content)
}

// ReadFile mocks base method.
func (m *MockFileOperator) ReadFile(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockFileOperatorMockRecorder) ReadFile(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockFileOperator)(nil).ReadFile), ctx, path)
}
